version: 2
updates:
- package-ecosystem: pip-compile
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  labels:
    - "engineering"
    - "dependencies"
    - "backend"
    - "pip"
  files:
    - requirements.in
    - dev-requirements.in
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  labels:
    - "engineering"
    - "dependencies"
    - "frontend"
    - "npm"
