version: "{build}"

branches:

  only:

  - master

services:
  - postgresql

build: false

environment:
  nodejs_version: "8"
  DEBUG: True
  DJANGO_SECRET_KEY: secret
  DATABASE_URL: postgres://postgres:Password12!@localhost:5432/networkapi
  USE_S3: False
  CORS_WHITELIST: "*"
  XSS_PROTECTION: True
  CONTENT_TYPE_NO_SNIFF: True
  SET_HSTS: False
  SSL_REDIRECT: False
  X_FRAME_OPTIONS: DENY
  ALLOWED_HOSTS: localhost
  PULSE_API_DOMAIN: https://network-pulse-api-production.herokuapp.com
  PULSE_DOMAIN: www.mozillapulse.org
  NETWORK_SITE_URL: https://foundation.mozilla.org
  TARGET_DOMAIN: foundation.mozilla.org
  SHOW_TAKEOVER: false
  USE_CLOUDINARY: false

  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "SET PYTHONPATH=%APPVEYOR_BUILD_FOLDER%"
  - ps: Install-Product node $env:nodejs_version
  - "npm install -g npm@latest"
  - "npm ci"
  - "python -m pip install --upgrade pip"
  - "python -m pip install pipenv"
  - "python -m pipenv install --dev --deploy"
  - "python -m pipenv run python network-api/manage.py collectstatic --no-input"

test_script:
  - node --version
  - npm --version
  - npm test
  - "python -m pipenv run flake8 tasks.py network-api/"
  - "python -m pipenv run python network-api/manage.py test"

cache:
  - "%APPDATA%\\npm-cache"
  - "%LOCALAPPDATA%\\pip\\Cache"

clone_depth: 1
